# Generated by Django 3.2.3 on 2023-06-18 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='Do your work')),
                ('category', models.CharField(default='To Do', max_length=50)),
                ('color', models.CharField(default='#FFFFFF', max_length=7)),
                ('assigned_to_names', models.CharField(blank=True, max_length=255, null=True)),
                ('deadline', models.DateField()),
                ('priority', models.CharField(choices=[('U', 'Urgent'), ('M', 'Medium'), ('L', 'Low')], default='M', max_length=1)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('inProgress', 'In Progress'), ('awaitingFeedback', 'Awaiting Feedback'), ('done', 'Done')], default='todo', max_length=16)),
                ('assigned_to', models.ManyToManyField(related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
